#!/bin/bash
base_url="https://adventofcode.com"

cmd="$1"
if [ $# -eq 1 ]
then
	day=$(date +%d)
	year=$(date +%Y)
elif [ $# -eq 2 ]
then
	day=$2
	year=$(date +%Y)
else
	year=$2
	day=$3
fi

run () {
	if [ -f "$1.jl" ]
	then
		julia $1.jl $2
	elif [ -f "$1.cpp" ]
	then
		make $1
		./exec/${1/\//-} $2
	elif [ -f "$1.py" ]
	then
		python $1.py $2
	fi
}

url="${base_url}/${year}/day/$((10#$day))"

if [ $cmd = "download" ]
then
	curl --cookie $(<.cookie) "${url}/input" > ${year}/inputs/${day};
elif [ $cmd = "run" ]
then
	filename=${year}/${day}
	run "${year}/${day}" "${year}/inputs/${day}"
elif [ $cmd = "test" ]
then
	run "${year}/${day}" "${year}/inputs/test"
elif [ $cmd = "commit" ]
then
	git add ${year}/${day}* && git commit -m "AoC ${year} - Day ${day}"
elif [ $cmd = "setup" ]
then
	cp template.jl ${year}/${day}.jl
fi
